### ISSUE TITLE
[BUG] - I have objective c and swift code, but when I have import ____-Swift.h, I get multiple errors generated because of parse issues with your framework

### ISSUE THREAD

**Issue by recoveryawareness** [admiral-team/admiralui-ios#723]
[BUG] - I have objective c and swift code, but when I have import ____-Swift.h, I get multiple errors generated because of parse issues with your framework.

**Comment by ton252** [comment]
How you connect this framework to your project? Could you send the example project with this bug?

**Comment by Almazovivan** [comment]
Ensure that the bridging header file is correctly configured and has been included in your Objective-C code. Check that the bridging header file is included in the "Objective-C Bridging Header" section of your project's build settings.

If you are still encountering issues, try cleaning your project and rebuilding it from scratch. This can often resolve build issues that occur due to outdated or corrupt build files.

If none of these solutions work, you may need to provide more details about the specific errors you are encountering, as well as the code that is causing them. This can help us in identifying the root cause of the issue and finding a solution.
